export const Colors = {
  light: {
    background: 'light-background',
    backgroundCode: '#ffffff',
    foreground: 'light-foreground',
    foregroundCode: '#111',
    card: 'light-card',
    cardCode: 'rgba(123, 123, 123, 0.15)',
    cardForeground: 'light-card-foreground',
    cardForegroundCode: '#111',
    popover: 'light-popover',
    popoverCode: '#ffffff',
    popoverForeground: 'light-popover-foreground',
    popoverForegroundCode: '#111',
    primary: 'light-primary',
    primaryCode: '#49B618',
    primaryForeground: 'light-primary-foreground',
    primaryForegroundCode: '#EEEEEE',
    secondary: 'light-secondary',
    secondaryCode: '#C9D72E',
    secondaryForeground: 'light-secondary-foreground',
    secondaryForegroundCode: '#EEEEEE',
    muted: 'light-muted',
    mutedCode: 'rgba(123, 123, 123, 0.5)',
    mutedForeground: 'light-muted-foreground',
    mutedForegroundCode: 'rgba(255, 255, 255, 0.5)',
    accent: 'light-accent',
    accentCode: '#C9D72E',
    accentForeground: 'light-accent-foreground',
    accentForegroundCode: '#EEEEEE',
    destructive: 'light-destructive',
    destructiveCode: '#d71344',
    destructiveForeground: 'light-destructive-foreground',
    destructiveForegroundCode: '#EEEEEE',
    border: 'light-border',
    borderCode: 'rgba(85, 85, 85, 0.15)',
    input: 'light-input',
    inputCode: 'rgba(85, 85, 85, 0.15)',
    ring: 'light-ring',
    ringCode: '#49B618',
    text: 'light-text',
    textCode: '#000000'
  },
  dark: {
    background: 'dark-background',
    backgroundCode: '#111',
    foreground: 'dark-foreground',
    foregroundCode: '#EEEEEE',
    card: 'dark-card',
    cardCode: 'rgba(123, 123, 123, 0.15)',
    cardForeground: 'dark-card-foreground',
    cardForegroundCode: 'hsl(210, 40%, 98%)',
    popover: 'dark-popover',
    popoverCode: 'rgb(0, 0, 0)',
    popoverForeground: 'dark-popover-foreground',
    popoverForegroundCode: '#EEEEEE',
    primary: 'dark-primary',
    primaryCode: '#49B618',
    primaryForeground: 'dark-primary-foreground',
    primaryForegroundCode: '#EEEEEE',
    secondary: 'dark-secondary',
    secondaryCode: '#C9D72E',
    secondaryForeground: 'dark-secondary-foreground',
    secondaryForegroundCode: '#EEEEEE',
    muted: 'dark-muted',
    mutedCode: 'rgba(123, 123, 123, 0.5)',
    mutedForeground: 'dark-muted-foreground',
    mutedForegroundCode: 'rgba(255, 255, 255, 0.5)',
    accent: 'dark-accent',
    accentCode: '#49B618',
    accentForeground: 'dark-accent-foreground',
    accentForegroundCode: '#EEEEEE',
    destructive: 'dark-destructive',
    destructiveCode: '#d71344',
    destructiveForeground: 'dark-destructive-foreground',
    destructiveForegroundCode: '#EEEEEE',
    border: 'dark-border',
    borderCode: 'rgba(85, 85, 85, 0.15)',
    input: 'dark-input',
    inputCode: 'rgba(85, 85, 85, 0.4)',
    ring: 'dark-ring',
    ringCode: '#49B618',
    text: 'dark-text',
    textCode: '#EEEEEE'
  }
};
